name: "build"

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: "build"
        run: make
      - name: "check"
        run: make check
      - name: "zip"
        run: zip -r vfu.zip build/Release/vfu.app
      - name: "archive outputs"
        uses: actions/upload-artifact@v4
        with:
          name: vfu
          path: vfu.zip
