name: "bundle"

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  package:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: "build"
        run: make VERS=${GITHUB_SHA}
      - name: "zip"
        run: cd build/Release && zip -r ../../vfu-arm64.zip vfu.app
      - name: "checksum"
        run: shasum -a 256 vfu-arm64.zip > vfu-arm64.zip.sha256
      - name: "archive outputs"
        uses: actions/upload-artifact@v4
        with:
          name: vfu
          path: |
            vfu-arm64.zip
            vfu-arm64.zip.sha256
  upload:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: vfu
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            vfu-arm64.zip
            vfu-arm64.zip.sha256
