name: "check"

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: "build"
        run: make FLAGS="-D CI_SKIP_NESTED_VIRT"
      - name: "check"
        run: make check
